#!/bin/bash
# shellcheck disable=1091

GH_EXTENSION_DIR="$HOME/.local/share/gh/extensions/gh-hooker"

. "$GH_EXTENSION_DIR/colors.sh"

set -euo pipefail

BINDIR="$HOME/.local/bin/gh-hooker"
mkdir -p "$BINDIR"
echo -e "$INFO Installing git extensions into $BINDIR/bin..."
cp -r "$GH_EXTENSION_DIR/bin" "$BINDIR"
echo -e "$INFO Installing git hooks into $BINDIR/hooks..."
cp -r "$GH_EXTENSION_DIR/hooks" "$BINDIR"

SHARE_DIR="$HOME/.local/share/gh-hooker"
mkdir -p "$SHARE_DIR"
echo -e "$INFO Installing git bootstrap files into $SHARE_DIR/bootstrap..."
cp -r "$GH_EXTENSION_DIR/bootstrap" "$SHARE_DIR"

echo -e "$SUCCESS Installation complete."
echo -e "$INFO Add $BINDIR/bin to PATH."

