#!/bin/bash
# shellcheck disable=1091

set -euo pipefail

GH_DIR=.

if [ "$(basename "${BASH_SOURCE[0]}")" != git-hooks-and-extensions ]
then
    if type -p gh
    then
        GH_DIR="$HOME/.local/share/gh/extensions/git-hooks-and-extensions"
    else
        echo -e "$ERROR Unknown executable."
        exit 1
    fi
fi


. "$GH_DIR/share/colors.sh"

BINDIR="$HOME/.local/bin/git-hooks-and-extensions"
mkdir -p "$BINDIR"
echo -e "$INFO Installing git extensions into $BINDIR/bin..."
cp -r "$GH_DIR/bin" "$BINDIR"
echo -e "$INFO Installing git hooks into $BINDIR/hooks..."
cp -r "$GH_DIR/hooks" "$BINDIR"

SHARE_DIR="$HOME/.local/share/git-hooks-and-extensions"
mkdir -p "$SHARE_DIR"
echo -e "$INFO Installing git bootstrap files into $SHARE_DIR/bootstrap..."
cp -r "$GH_DIR/share/bootstrap" "$SHARE_DIR"
cp "$GH_DIR/share/colors.sh" "$SHARE_DIR"

echo -e "$WARN Add $BINDIR/bin to PATH."

if command -v go-md2man > /dev/null
then
    MANDIR="$HOME/.local/share/man/man1"
    mkdir -p "$MANDIR"
    echo -e "$INFO Installing git extension man pages into $MANDIR..."
    for filename in "$GH_DIR"/man/*.md
    do
        file="$(basename "$filename")"
        go-md2man -in "$filename" -out "$MANDIR/${file%.*}".1
    done
    echo -e "$WARN Add $HOME/.local/share/man to MANPATH."
else
    echo -e "$WARN Man pages were not installed because \`go-md2man\` was not found in PATH."
    echo -e "$WARN To install:"
    echo -e "$WARN \t\tgo install github.com/cpuguy83/go-md2man/v2@latest"
fi

echo -e "$SUCCESS Installation complete."

