#!/bin/bash
# shellcheck disable=1091

set -euo pipefail

GH_DIR=.

if [ "$(basename "${BASH_SOURCE[0]}")" != git-hooks-and-extensions ]
then
    if type -p gh
    then
        GH_DIR="$HOME/.local/share/gh/extensions/git-hooks-and-extensions"
    else
        echo -e "$ERROR Unknown executable."
        exit 1
    fi
fi


. "$GH_DIR/share/colors.sh"

BINDIR="$HOME/.local/bin/git-hooks-and-extensions"
mkdir -p "$BINDIR"
echo -e "$INFO Installing git extensions into $BINDIR/bin..."
cp -r "$GH_DIR/bin" "$BINDIR"
echo -e "$INFO Installing git hooks into $BINDIR/hooks..."
cp -r "$GH_DIR/hooks" "$BINDIR"

SHARE_DIR="$HOME/.local/share/git-hooks-and-extensions"
mkdir -p "$SHARE_DIR"
echo -e "$INFO Installing git bootstrap files into $SHARE_DIR/bootstrap..."
cp -r "$GH_DIR/share/bootstrap" "$SHARE_DIR"
cp "$GH_DIR/share/colors.sh" "$SHARE_DIR"

MANDIR=/usr/share/man/man1
echo -e "$INFO Installing git man pages into $MANDIR..."
if [ $EUID -ne 0 ]
then
    sudo cp "$GH_DIR"/man/*.1 "$MANDIR"
else
    # When installig using a container, we don't need `sudo` as it runs as `root`.
    cp "$GH_DIR"/man/*.1 "$MANDIR"
fi

echo -e "$SUCCESS Installation complete."
echo -e "$INFO Add $BINDIR/bin to PATH."

